language: java
jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  
notifications:
  email:
    recipients:
      - martinsua24@gmail.com
      - lautaro.stroia@gmail.com
      - jpstrnisko@gmail.com
    on failure: always
 
